# extend = "*.ipynb"
# extend-include = ["*.ipynb"]
line-length    = 88
target-version = "py311"

fixable   = ["ALL"]
unfixable = []

ignore = [
    "D",
    "E4",
    "E5",
    "F4",
    "F821",
    "I",
    "W",
    "RET50",
    "C90",
    "TRY003",
    "COM812",
    "S10",
    "S3",
    "B007",
    "UP",
    "SIM",
    "PLR09",
    "PLR2004",
]

select = [
    "S",
    "B",
    "A",
    "COM",
    "DTZ",
    "T10",
    "EXE",
    "ISC",
    "ICN",
    "G",
    "INP",
    "PIE",
    "PYI",
    "PT",
    "RET",
    "SIM",
    "TID",
    "TCH",
    "PL",
    "TRY",
    "PD",
    "NPY",
]

exclude = [
    ".tox",
    ".venv",
    ".vim",
    ".virtual_documents",
    "build",
    "dist",
    "*migrations*",
    ".pytest_cache",
    ".git",
    "__pycache__",
    ".mypy_cache",
    ".ipynb_checkpoints",
    ".vscode",
    ".hypothesis",
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    "__pypackages__",
    "_build",
    "buck-out",
    "node_modules",
    "site-packages",
    "venv",
]

[mccabe]
    max-complexity = 10

[per-file-ignores]
    "__init__.py"             = ["E40", "F401"]
    "**/{tests,docs,tools}/*" = ["E40", "F401"]
