---
title: "qmd_stats for finance & markets-extended"
author: "Ernest Orlowski"
format:
  html:
  	code-fold: true
jupyter: "python3"
editor:
  markdown:
    wrap: 80
---

# Market Stats & Vol Analysis

## Quick Overview

1.  Normal Distribution & Its Limitations <!--(#Normal-Distribution-&-Its-Limitations) -->
Do stock returns follow a normal distribution? Almost certainly not. The distribution of asset prices is a product of intricate micro-market dynamics involving trade flow, pricing distributions(#note), and volumes. The primary issues to consider
are:
*   Asset returns exhibit `skewness` & `kurtosis` (fat tails).
*   Returns may display serial correlation, meaning successive returns aren't independent(#note).
*   Volatility isnt constant over time, it exhibits `heterscedasticity`, with Sharpe volatility clustering.
*   Relationships exist between volatility and asset returns, such as the `Leverage Effect`.


2. **CLT** Central Limit Theorem
The CLT is a fundamental theorem in statistics. It states that the distirbution of a sample mean of a sufficiently large number of independent and indentically distributed (i.i.d) random variables approaches a normal distribution, regardless of the original distribution of those variables.
  > Basically it suggests that if many random samples are taken and their means calculated, those means will tend to follow a bell-shaped, Gaussian curve, i.e. normal distribution.
  > Suppose $X_{1},X_{2},$... is a sequence of i.i.d random variables with $E[X_{i}] = \mu$ and $Var[X_{i}] = \sigma^{2} < \infty $
  > Let $S_{n} := \frac{ X_1+X_2+...X_n}{n} = \frac{\Sigma^{n} X_{i}}{n}$
  > Then as $n$ approaches $\infty$, the random variables $\sqrt{n}(S_{n}-\mu)$ converge in distribution to a normal $N(0,\sigma^{2}$. In other words, the distribution of $\sqrt{n}(S_{n}-\mu)$ is asymptotically normal with mean $0$ and variance $\sigma^{2}$.
  > $\sqrt{n}(\frac{1}{n} \Sigma^{n}_{i=1} X_{i} - \mu) \rightarrow N(0, \sigma^{2})$ as $n \rightarrow \infty$.

ref: [CLT image]("C://Users//eorlo/Desktop/CLT.png")

A great video to watch for a quick brush up is: [3B1B CLT](https://youtu.be/zeJD6dqJ5lo?si=g-G7aHhQn8PfqARX)

```{python}
import warnings; warnings.filterwarnings("ignore", module = "seaborn\..*")
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats

sns.set_theme()
colors = sns.color_palette()
colors += colors

no_port_mgrs = 12

no_returns = np.random.normal(loc = 20, scale = 8, size = no_port_mgrs)
means = np.random.normal(loc = 0.1, scale = 0.05, size = no_port_mgrs)
stds = np.random.normal(loc = 0.3, scale = 0.05, size = no_port_mgrs)
skews = np.random.randn(no_port_mgrs) * 0.5

ports = [stats.pearson3(loc = mean, scale = std, skew = sk) for mean, std, sk in zip(means, stds, skews)]

port_mgr = np.arange(no_port_mgrs)
shape_dim = [3, 4]

port_mgr = port_mgr.reshape(shape_dim)
fig, axs = plt.subplots(nrows=3, ncols=4, figsize = (12, 11))

port_returns = {}

for (x, y), port in np.ndenumerate(port_mgr):
    years = int(no_returns[port])
    port_returns[port] = ports[port].rvs(size = int(years))
    sns_dist = sns.histplot(port_returns[port], bins = 10, kde = True, ax = axs[x, y], color = colors[port_mgr[x][y]])
    axs[x, y].set_title(f"Mgr {port_mgr[x][y]}, {years} yrs")
    axs[x, y].set_xlim(-1, 1)

fig.suptitle('Comparison of portfolio managers returns')

```


<!-- 1.  [Volatility](#Volatility) -->
