name: ThinkBayes2
channels:
  - conda-forge
  - fastai
  - nodefaults
dependencies:
  - python>=3.6
  - jupyter
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - statsmodels
  - scipy
  - pymc3
  - arviz
  - python-graphviz
  - mkl-service
  - lxml
  - xlrd
  - html5lib
  - pytables
  - nbconvert
  - pandoc<2.3
  - fastai::fastdoc
  - pip
  - jupyter_nbextensions_configurator
  - pytest
  - nbmake
  - jupyter-book
  - ghp-import
  - empiricaldist>=0.6.7
